[project]
name = "zpools-cli"
version = "0.1.0"
description = "Command line interface for zpools.io"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "zpools-sdk",
    "typer",
    "rich",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
zpools = "zpools_cli.main:app"

[tool.uv.sources]
zpools-sdk = { workspace = true }
